### ISSUE TITLE
Lets Add Speed Test in the app so that it can help to get rid of extra app.

### ISSUE THREAD

**Issue by aishwarya85** [itsdrnoob/DataMonitor#1]
**Adding speed test in the same app will enhance the feature of the app and customers can check whether data is working or not.**

https://play.google.com/store/apps/details?id=com.gyokovsolutions.gnettracklite&hl=en_IN&gl=US

This is a sample app which gives detailed analytics of speed as well as location.

We can also add a simple speed test if the above app feature is difficult to do.

**Comment by itsdrnoob** [comment]
Sure thing, I'll check that out

**Comment by aishwarya85** [comment]
Thank you

**Comment by itsdrnoob** [comment]
Repo updated and a [new version](https://github.com/itsdrnoob/DataMonitor/releases/tag/v1.5) has been released.
