### ISSUE TITLE
Add Monero (XMR) donation address

### ISSUE THREAD

**Issue by nahuhh** [itsdrnoob/DataMonitor#104]
### Checklist

- [X] I made sure that there are no similar feature requests - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details in an appropriate descriptive way. I understand that the feature request will be dismissed otherwise.
- [x] This issue contains only one feature request.

### Describe the Feature you'd like

Addition of a donation address for Monero aka XMR

### Why do you want this feature?

1. The other options arent private at all. 
2. Eth and btc can be expensive
3. Monero is fast and cheap to use, (more) stable price action, p2p privacy (we cannot monitor one anothers balances or activity, and vice versa. Like fiat). 

### Additional context

You can create a monero wallet using the official desktop GUI or CLI from getmonero.org, or a trusted 3rd party wallet (by a monero dev) Feather wallet.
On mobile you can use Cake Wallet or Stack Wallet.

**Comment by itsdrnoob** [comment]
Thanks for the info, will take a look at it.
