### ISSUE TITLE
Add ability to set start time and end time of daily data

### ISSUE THREAD

**Issue by killerrook** [itsdrnoob/DataMonitor#108]
### Checklist

- [X] I made sure that there are no similar feature requests - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details in an appropriate descriptive way. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Describe the Feature you'd like

Add an option to set start time and end time for the data usage calculation of each day.

### Why do you want this feature?

A lot of service providers provides a variable end time for daily data plan e.g in some vendors data reset at 12:30 midnight others at 12:45 midnight 

### Additional context

Nothing here just crickets

**Comment by itsdrnoob** [comment]
> A lot of service providers provides a variable end time for daily data plan e.g in some vendors data reset at 12:30 midnight others at 12:45 midnight

There is an option in "Setup" to change the daily data reset time.
