### ISSUE TITLE
Network speed display in Notification panel.

### ISSUE THREAD

**Issue by subham2024** [itsdrnoob/DataMonitor#11]
Request for live network speed display in notification bar.
Network speed should be always displayed on notification bar like time is displayed.
While dropping the notification area, it should be able to display upload and download speed.

For example [Internet Speed Meter Lite](https://play.google.com/store/apps/details?id=com.internet.speed.meter.lite)

**Comment by hackevil** [comment]
Just came to open an issue about it, it would be really neat to have that feature.

**Comment by Pranab009** [comment]
Yes Please add this feature.
This app is too good.
Only this feature is missing.
Please add this feature and complete the app.

![Screenshot_20220730-150703_1](https://user-images.githubusercontent.com/65340361/181904683-27de76e1-ecc8-42f4-9566-d216e36fd1f0.png)

**Comment by itsdrnoob** [comment]
> Yes Please add this feature. This app is too good. Only this feature is missing. Please add this feature and complete the app.

I'm glad you liked the application. Network speed notification is on my to-do list.

**Comment by Pranab009** [comment]
Thanks for your reply.
Please  work on it.
