### ISSUE TITLE
Incorrect app displayed for data usage?

### ISSUE THREAD

**Issue by twizzlebizzle** [itsdrnoob/DataMonitor#113]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/itsdrnoob/DataMonitor/releases/latest).
- [X] I made sure that there are no existing issues - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details in an appropriate descriptive way. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected app version

v2.2.0

### Steps to reproduce the bug

Used some mobile data in fennec browser.
Speed test (fast.com)

### Expected behavior

Data usage today should show 100mb+ in fennec

### Actual behavior

Fennec doesn't show any data use at all
Instead wireguard is showing as the data user when I'm not connected via wireguard.

### Screenshots/Screen recordings

Below screenshot shows the android data usage and the app data usage for comparison.  
![Screenshot1](https://user-images.githubusercontent.com/11423542/210787725-54b1e220-d9c8-4712-af72-e6018e1afed2.png) 

  
![Screenshot_20230105-131056](https://user-images.githubusercontent.com/11423542/210787877-50bb0f99-9ed4-4d39-aa13-9e361ff1ee60.png)

### Affected Android/Custom ROM version

13 (2023-01-05 patch)

### Affected device model

Pixel 7 Pro

### Additional context

I can't see Fennec at all in any of the days data usage
  It just seems absent

**Comment by itsdrnoob** [comment]
Tried it out and it's working fine on my end. Can you clear the app's data and recheck?

**Comment by twizzlebizzle** [comment]
> Tried it out and it's working fine on my end. Can you clear the app's data and recheck?

Don't know why I didn't try that, clearing app data sorted it.  Not sure why it did it though

**Comment by itsdrnoob** [comment]
> Don't know why I didn't try that, clearing app data sorted it.

Great

> Not sure why it did it though

Probably because Fennec was not initially added to the apps database.

Closing this as completed now

**Comment by twizzlebizzle** [comment]
No problems, so would I need to clear app data if I install new apps?

**Comment by itsdrnoob** [comment]
> would I need to clear app data if I install new apps?

Not really, new apps will be automatically added while refreshing the data. But in case you ever face such issues again, clearing the data might help.
