### ISSUE TITLE
Improve Live Speed Calculation

### ISSUE THREAD

**Issue by anuraag488** [itsdrnoob/DataMonitor#117]
Hi
Current approach uses getTotalRxBytes and getTotalTxBytes. Drawback of this approach is double speed is shown when real vpn is connected. You can use [LineageOS](https://github.com/LineageOS/android_lineage-sdk/blob/lineage-20.0/sdk/src/java/org/lineageos/internal/statusbar/NetworkTraffic.java) method to improve this. It uses getTxBytes(iface) to calculate speed.

**Comment by itsdrnoob** [comment]
Thanks, will check it out.
