### ISSUE TITLE
Can't translate on Transifex

### ISSUE THREAD

**Issue by Mosney** [itsdrnoob/DataMonitor#12]
> This organization has too many words and has been temporarily disabled. To resume using Transifex, please have an organization administrator upgrade to another plan.

**Comment by Terkyz** [comment]
I have the same problem, and I don't know how to do a fork and translate it...

**Comment by itsdrnoob** [comment]
I just noticed the issue. My transifex account was closed. Have to find another translation service. Till then forking the repo and adding translations, and then opening a pull request is the only solution.

**Comment by itsdrnoob** [comment]
@Mosney @Terkyz 
Try transating here: [Poeditor](https://poeditor.com/join/project/Z4nMRfIJ2s)

**Comment by Terkyz** [comment]
Can you please add Spanish as an option to translate?

**Comment by itsdrnoob** [comment]
> Can you please add Spanish as an option to translate?

Done
