### ISSUE TITLE
Add Polish to Weblate

### ISSUE THREAD

**Issue by tadekdudek** [itsdrnoob/DataMonitor#124]
I want to translate this app to Polish. Is it possible to add it to Weblate?

**Comment by itsdrnoob** [comment]
> Is it possible to add it to Weblate?

Yes it is. You need to log in to weblate, visit the [translation page](https://hosted.weblate.org/git/datamonitor/strings/), and when you scroll down, you can see the "Start new translation" button which you can use to add a new language.
