### ISSUE TITLE
Reported total usage not matching

### ISSUE THREAD

**Issue by jjreyes92** [itsdrnoob/DataMonitor#126]
The reported total usage is not matching (or even coming close) to the sum of the individual usages listed by app. For instance, today at this moment when I haven't been using the phone much, the total WIFI usage says ~2GB when the sum of all the reported WIFI usages by app comes to ~256 MB. What could be an explanation for this?

**Comment by itsdrnoob** [comment]
Let me check it and get back to you.

**Comment by itsdrnoob** [comment]
@jjreyes92 Do you have any applications added to the "Excluded Apps" list? As that could cause variations in both calculations. Also is this recurring issue?

**Comment by Aarekaz** [comment]
Similar issue here! ![Screenshot_20230201-091656.png](https://user-images.githubusercontent.com/36888347/215939163-da51478a-7f93-466a-b204-d84bcd27b59d.png)

![Screenshot_20230201-091153.png](https://user-images.githubusercontent.com/36888347/215939162-a62ba52d-6621-49a9-b522-9a8cbec8cd27.png)

No apps excluded

**Comment by jjreyes92** [comment]
@itsdrnoob 

No excluded apps but i figured out the issue. I have a second profile on my phone. I had the app installed on my main profile but not on the second. It takes into account total usage on the secondary profile but doesn't list the individual apps and their usages from the second profile. I installed the app on my secondary profile and checked the usage on there. Now it checks out better when i combine the listed usages on both profiles. If i assume you use 1000 MB = 1GB, the individual usages for today overshoot a bit to 2.76197 GB and if i assume you use 1024 MB = 1 GB then they undershoot a bit to 2.72911 GB when the reported total usage is  2.74 GB. Is there any other reason they wouldnt match up exactly? But anyway, sorry if i wasted your time looking for basically a nonissue.

**Comment by itsdrnoob** [comment]
> Is there any other reason they wouldnt match up exactly?

AFAIK, no. The results are exactly what's returned by the system. And data used in secondary profiles won't be shown in total usage in the primary profile anymore.
