### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Donga2020** [itsdrnoob/DataMonitor#127]
----------Start of crash----------
Thread name: Timer-275
Thread stacktrace: [dalvik.system.VMStack.getThreadStackTrace(Native Method),
 java.lang.Thread.getStackTrace(Thread.java:1841),
 e.c.a.f.a.uncaughtException(Unknown Source:47),
 java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073),
 java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068),
 java.lang.Thread.dispatchUncaughtException(Thread.java:2306)]
crash message: Drawable resource ID must not be 0

----------Crash logs----------
[androidx.core.graphics.drawable.IconCompat.b(:2),
 com.drnoob.datamonitor.utils.LiveNetworkMonitor.a(:6),
 com.drnoob.datamonitor.utils.LiveNetworkMonitor$b.run(Unknown Source:19),
 java.util.TimerThread.mainLoop(Timer.java:563),
 java.util.TimerThread.run(Timer.java:513)]

----------Device info----------
Device Manufacturer: samsung
Device Brand: samsung
Device Model: SM-A125F
Device Codename: a12nnxx
Android version: 12, 31
SOC Model: MT6765V/CB

**Comment by itsdrnoob** [comment]
It seems like you're running an older version of the app. Update to the latest version and see if the issue persists.

**Comment by Donga2020** [comment]
Thanks
