### ISSUE TITLE
Data usage alert not working

### ISSUE THREAD

**Issue by Cypher-Emm** [itsdrnoob/DataMonitor#128]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/itsdrnoob/DataMonitor/releases/latest).
- [X] I made sure that there are no existing issues - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details in an appropriate descriptive way. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected app version

v2.2.0

### Steps to reproduce the bug

Install Data Monitor v2.2.0
Give usage data access and disable battery optimisation
Add data plan (daily) and set plan reset time
Turn on data usage alert and set trigger level (tried with both default 85% and custom ones too)
You will notice that it only works for the first time(on day one) and won't alert the next day

### Affected Android/Custom ROM version

Android 11 One UI 3.1 Stock (ARMv7)

### Affected device model

Samsung Galaxy A10 (A105F)

### Additional context

Can anyone else reproduce.
Tried everything but it always works only on day 1

**Comment by itsdrnoob** [comment]
I'll check if there's any issue with it.
