### ISSUE TITLE
Show connection speed in the status bar

### ISSUE THREAD

**Issue by mecuricat** [itsdrnoob/DataMonitor#129]
### Checklist

- [X] I made sure that there are no similar feature requests - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details in an appropriate descriptive way. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Describe the Feature you'd like

Display live network speed in the status bar.

![status bar icons](https://user-images.githubusercontent.com/89805719/216628790-2025b599-819c-480f-ac14-1cddbbcfa39f.jpg)

### Why do you want this feature?

It helps in identifying whether data is being abused and prevent excessive data usage beforehand. An advantage of displaying network speed on the status bar: Unless you know some app is abusing data in background, you won't go looking for it, would you?

**Comment by itsdrnoob** [comment]
> Display live network speed in the status bar.

Have you tried out "Live network speed"? I believe that's exactly what you're talking about.

**Comment by mecuricat** [comment]
I applied the feature. It is missing from the status bar and only visible on the notification drawer which you have to pull to see. Is this the expected behavior?

<img src="https://user-images.githubusercontent.com/112750975/216635118-926e4b89-20b7-4f11-b5c5-5e810603cd46.jpg" height="300px"/>

<img src="https://user-images.githubusercontent.com/112750975/216635186-8b99e12c-c0ef-4054-94c5-ff766ec9f443.jpg" height="300px"/>

**Comment by itsdrnoob** [comment]
> Is this the expected behavior?

No, it's not. 

![Screenshot_20230203-204605_Chrome](https://user-images.githubusercontent.com/52557407/216639233-7b937f82-5599-49ed-9bcb-a4d045bbe2f8.png)
This is how it's supposed to look like.

Have you disabled notification icons?
Does data usage notification show up on the status bar?

**Comment by mecuricat** [comment]
Do you mean this?

<img src="https://user-images.githubusercontent.com/112750975/216643846-80ae0746-29ce-4cbd-950d-ace371185903.jpg" height="300px"/>

Still missing.

**Comment by itsdrnoob** [comment]
> Still missing.

Strange. Are other apps (non-system) working fine?

**Comment by mecuricat** [comment]
I am sorry I did not understand. What did you mean?

Do you think it's device specific?

**Comment by mecuricat** [comment]
I enabled notification icons for status bar. That's what you meant right?

It works. Thanks. :)

I would like to open a few issues as a follow up.
