### ISSUE TITLE
Set a data plan date

### ISSUE THREAD

**Issue by Terkyz** [itsdrnoob/DataMonitor#13]
**Is your feature request related to a problem? Please describe.**
Yes. When adding or editing a data plan, I can only define a time, but not a date...

**Describe the solution you'd like**
When selecting a "monthly" plan, a option appear to choose which month and which day the data plan expires.

**Describe alternatives you've considered**
The default calendar application opens to choose which day the plan expires.

**Additional context**
That's all.

**Comment by itsdrnoob** [comment]
As of now, when selecting a monthly plan, the 1st day of the month is considered as the data refresh date.
