### ISSUE TITLE
Make Usage Access permission optional

### ISSUE THREAD

**Issue by mecuricat** [itsdrnoob/DataMonitor#131]
### Checklist

- [X] I made sure that there are no similar feature requests - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details in an appropriate descriptive way. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Describe the Feature you'd like

Please make Usage Access permission optional for app functionality

### Why do you want this feature?

If I wish to use Data Monitor for the sole purpose of displaying connection speed in the status bar, I wouldn't need to provide the highly sensitive Usage Access permission.

**Comment by itsdrnoob** [comment]
Well that would defeat the sole purpose of the app. It's primary objective is to monitor one's data usage, for which Usage access permission is necessary.

I do understand your concern about granting the permission but no data collected using it ever leaves your device. Everything is stored locally and fetched from the system when needed.

**Comment by mecuricat** [comment]
I understand. Can you clarify why Data Monitor requires  full network access?

**Comment by itsdrnoob** [comment]
> Can you clarify why Data Monitor requires full network access?

Network access required to run Network diagnostics.
