### ISSUE TITLE
Show connection speed in the status bar when notification drawer is pulled down

### ISSUE THREAD

**Issue by mecuricat** [itsdrnoob/DataMonitor#132]
### Checklist

- [X] I made sure that there are no similar feature requests - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details in an appropriate descriptive way. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Describe the Feature you'd like

Please show connection speed in the status bar when notification drawer is pulled down

### Why do you want this feature?

When you pull down the notification drawer, the connection speed disappears from status bar and appears as a notification instead. Is this expected behavior?

<img src="https://user-images.githubusercontent.com/112750975/216665362-16c3dac3-0934-4d77-a522-9862b4d0a588.jpg" height="300px"/>

The notification drawer can hardly fit 3-4 notifications. As such, I would prefer not to have a permanent notification in the drawer. But I can't disable notification for Network Speed Monitor because then the speed icon from status bar also disappears.

Is there a solution to this?

**Comment by itsdrnoob** [comment]
> Is this expected behavior?

Yes, this is an expected behavior.

> Is there a solution to this?

There's no straight forward solution for this. Third party apps cannot modify the system elements (status bar in this case) without root permissions.

**Comment by mecuricat** [comment]
I see. The same is the case with [Net Monitor by Hu Shenghao](https://play.google.com/store/apps/details?id=com.dede.nativetools).

Should this issue be open? Please close this issue as you see fit.
