### ISSUE TITLE
Show network speed horizontally instead of vertically

### ISSUE THREAD

**Issue by mecuricat** [itsdrnoob/DataMonitor#133]
### Checklist

- [X] I made sure that there are no similar feature requests - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details in an appropriate descriptive way. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Describe the Feature you'd like

Please show network speed horizontally instead of vertically for better visibility

### Why do you want this feature?

The current implementation looks like this:

<img src="https://user-images.githubusercontent.com/112750975/216666464-5b679a08-7ee9-42c0-9ea7-6e5d485295ca.jpg" height="300px"/>

This is kind of hard to see. Since it is vertical, any resizing would not fit the status bar properly. If implemented horizontally, it would look like below:

<img src="https://user-images.githubusercontent.com/112750975/216667682-921e4393-d0d5-4348-950a-7a9004162441.jpg" height="300px"/>

### Additional context

Please consider this feature.

**Comment by itsdrnoob** [comment]
Notification icons are restricted to a certain dimension so that it stays even accross every app.

> implemented horizontally, it would look like below:

That is built into the system and is not a notification icon.

**Comment by mecuricat** [comment]
Oh no. My last cry for hope is that AOSP relaxes such conditions. Same for issue 132.
