### ISSUE TITLE
Data usage 

### ISSUE THREAD

**Issue by rajarshikhatua** [itsdrnoob/DataMonitor#139]
### Checklist

- [X] I made sure that there are no similar feature requests - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details in an appropriate descriptive way. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Describe the Feature you'd like

Shows data usage in app notification. see the below picture 
![Screenshot_20230228_012441_Data Monitor](https://user-images.githubusercontent.com/77912617/221678339-6db81989-edf3-4007-9a2c-af77a3719f6c.jpg)

### Why do you want this feature?

users don't have to open the app each time they want to see data usage 

### Additional context

see the below picture to see how the notification will look like 
![20230228_015211](https://user-images.githubusercontent.com/77912617/221678398-7cabadde-6023-4050-994c-62d4fb3e2539.jpg)

**Comment by itsdrnoob** [comment]
Check out Combined notification.
