### ISSUE TITLE
Live network speed per app

### ISSUE THREAD

**Issue by ghost** [itsdrnoob/DataMonitor#146]
### Checklist

- [X] I made sure that there are no similar feature requests - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details in an appropriate descriptive way. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Describe the Feature you'd like

The live network speed feature is great, and is the majority of why I chose this app over other data usage apps. It would be great if it was somehow possible to indicate which app is consuming the data at that moment.

### Why do you want this feature?

Sometimes it's hard to tell which app is consuming data in the background. Knowing this can help with app choices, as well as being alert that something malicious could be going on with an app in real time.

**Comment by AbhiTheModder** [comment]
@prayingmantis287 It's obvious that the app which you using at that moment will be using your data 😕

**Comment by ghost** [comment]
@AbhiTheModder Of course, but even with all apps closed there are apps that run in the background such as email, social media, and data syncing apps. The live network speed feature makes it apparent of exactly when these data-consuming background processes are occurring.

**Comment by AbhiTheModder** [comment]
@prayingmantis287 those apps only use 2-5kb data maximum 5mb if app starts showing so much usage then it'll malfunction because Android itself uses data regularly like play services,ps,speech engine 

it'll lag

**Comment by ghost** [comment]
@AbhiTheModder Agreed. However, my request for the feature enhancement isn't so much to determine which apps are consuming a large amount of data at one time, but rather which ones are actively using any amount of data at any given time. Essentially it would give a network monitoring ability per app.

**Comment by AbhiTheModder** [comment]
@prayingmantis287 🫤Let the dev decide :) me quit

**Comment by itsdrnoob** [comment]
Valid request, but in order to do so, live network monitor would have to fetch the usage of each and every app to determine which one is consuming data. The process itself might take anywhere from 1 second to 5 seconds or more depending on the user's device and the number of apps installed. Now imagine invoking the function every second. Also, there could be a bunch of apps fetching data in the background at the same time.

Overall, while it is technically possible, it's not quite feasible to do so.

**Comment by AbhiTheModder** [comment]
> 

This is what I was trying to state also.

**Comment by ghost** [comment]
@itsdrnoob I see. Thank you for the explanation.
