### ISSUE TITLE
separate plans for different sims

### ISSUE THREAD

**Issue by alihsabdullatif** [itsdrnoob/DataMonitor#149]
### Checklist

- [X] I made sure that there are no similar feature requests - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details in an appropriate descriptive way. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Describe the Feature you'd like

I have 2 sims with different data plans, would be amazing if I could track them separately instead of both together (they are different in size) so when I change the active data sim the app can start adding to the selected plan 

### Why do you want this feature?

I travel regularly and need 2 sims for different regions 

### Additional context

-

**Comment by itsdrnoob** [comment]
The API to track data usage of individual SIM cards is restricted to third party apps since android 10. So there's not much I can do.

**Comment by alihsabdullatif** [comment]
ok thanks I'll close this

**Comment by Cwpute** [comment]
There could a workaround for this, if the user was able to set up two different plans, and manually switch between them when it's needed.
Would that be a good enough solutiwn for you @alihsabdullatif ?
