### ISSUE TITLE
Notification visibility 

### ISSUE THREAD

**Issue by rajarshikhatua100** [itsdrnoob/DataMonitor#15]
The data notification is not visible if the notification panel is not opened; design the notification in such a way that it always visible from anywhere
![20220724_171442](https://user-images.githubusercontent.com/77912617/180645408-7f87f1c5-b7af-449d-b3d7-420d5b16fe6f.jpg)
like the attached image

**Comment by itsdrnoob** [comment]
You mean the data usage is not visible if the notification is not expanded manually?

**Comment by subham2024** [comment]
> You mean the data usage is not visible if the notification is not expanded manually?

Yes .
When notification gets expanded then only data usage gets visible.
As you can see the differences in image , first notification is from Internet Speed Meter Lite app and second notification is from Data Monitor app.
Both are not expanded.
![Screenshot_20220724-202749_One UI Home](https://user-images.githubusercontent.com/97289856/180653012-f174bd1b-1bf5-47eb-84f6-77e947158842.jpg)

**Comment by itsdrnoob** [comment]
Okay got it. Will add this in the next update.

**Comment by rajarshikhatua100** [comment]
yes exactly that✅✅
