### ISSUE TITLE
Widget always shows 0 MB of mobile data usage 

### ISSUE THREAD

**Issue by ivomod** [itsdrnoob/DataMonitor#150]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/itsdrnoob/DataMonitor/releases/latest).
- [X] I made sure that there are no existing issues - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details in an appropriate descriptive way. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected app version

v2.2.0

### Steps to reproduce the bug

1. Use phone with two SIMs (not sure if relevant).
2. Add widget to the home screen.
3. Observe 0 MB usage of mobile data:

![Screenshot_20230314_184958_One UI Home](https://user-images.githubusercontent.com/37458586/225095040-6abc7c1c-e6e5-4106-b5b9-3f59dfac109f.png)

5. Click widget.
6. Apps shows the proper data usage: 

![Screenshot_20230314_185009_Data Monitor](https://user-images.githubusercontent.com/37458586/225095179-f734dc1e-5e77-4962-9d5f-3eaffd46bc79.png)

### Expected behavior

Both widget and app should show same stats.

### Actual behavior

The widget shows 0MB, different what the app shows.

### Affected Android/Custom ROM version

Android 13 / OneUI 5.1

### Affected device model

Samsung Galaxy S23

**Comment by itsdrnoob** [comment]
Did you add a data plan?

**Comment by ivomod** [comment]
> Did you add a data plan?

That fixed the issue, however I would expect that the widget should count data without a data plan.

**Comment by itsdrnoob** [comment]
> widget should count data without a data plan.

It does. Fixed in beta. 2eb03a0

**Comment by ivomod** [comment]
> > widget should count data without a data plan.
> 
> It does. Fixed in beta. [2eb03a0](https://github.com/itsdrnoob/DataMonitor/commit/2eb03a0122172b1ef9b0d2912ec9fe14513611c2)

Confirmed it works in beta. Thanks
