### ISSUE TITLE
System Apps entry in App data usage tab is not opening when opening the app via tapping the widget.

### ISSUE THREAD

**Issue by subham2024** [itsdrnoob/DataMonitor#17]
**Describe the bug**
System Apps entry in App data usage tab is not opening when opening the app via tapping the widget in the homesreen.

**To Reproduce**
1. Add widget to homescreen
2. Tap on the widget to open the app
3. Go to App data usage tab in middle of the bottom panel
4. Tap on System Apps entry

**Expected behavior**
Opening of System Apps entry which shows data usage by each system app separately.

**Smartphone :**
 - Device: Samsung Galaxy M32
 - OS: One UI 4.1 , Android 12
 - Version One UI 4.1

**Additional context**
When opening the app using normal way i.e. by tapping the app icon in application menu, System Apps is opening as intended.

**Comment by itsdrnoob** [comment]
Thanks for mentioning the issue. I'll surely look into it. Currently a bit busy with my exams.

**Comment by subham2024** [comment]
> Thanks for mentioning the issue. I'll surely look into it. Currently a bit busy with my exams.

Were you able to reproduce the bug?

**Comment by itsdrnoob** [comment]
> > Thanks for mentioning the issue. I'll surely look into it. Currently a bit busy with my exams.
> 
> Were you able to reproduce the bug?

Yes
