### ISSUE TITLE
Incorrect app usage data

### ISSUE THREAD

**Issue by nexsych** [itsdrnoob/DataMonitor#170]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/itsdrnoob/DataMonitor/releases/latest).
- [X] I made sure that there are no existing issues - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [x] I have taken the time to fill in all the required details in an appropriate descriptive way. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected app version

2.3.1

### Steps to reproduce the bug

Already knew brave has used that much MB

Checked on this app's app usage tab

checked on glasswire

### Actual behavior

This app has some major problems: It shows false report about app usage: It shows an app named vanced microg has used around 800 MB mobile data while it haven't. I have downloaded a file of 800 MB from brave browser but it doesn't show brave in the app usage anywhere instead show brave's usage as of microg's. I just checked with glass wire (and have taken screenshots)

**Comment by itsdrnoob** [comment]
It could happen due to issues with the app database. Clear the app data or reinstall the app and check if it solves the issue.
