### ISSUE TITLE
Third party icon support

### ISSUE THREAD

**Issue by Vyshnav57** [itsdrnoob/DataMonitor#171]
### Checklist

- [X] I made sure that there are no similar feature requests - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details in an appropriate descriptive way. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Describe the Feature you'd like

It'd be great if there was support for third party icon packs in-app, that is the app icons showing up within the app would adhere to the third party icon pack which is applied system wide

### Why do you want this feature?

I think it helps with the app blend in more with the rest if the system

**Comment by itsdrnoob** [comment]
Support for third party icon packs is outside the scope of the app, and is dependent on the developer of such icon packs.
I'd suggest that you reach out to the icon pack's developer for the same.
