### ISSUE TITLE
Daily quota alert

### ISSUE THREAD

**Issue by VinNgase** [itsdrnoob/DataMonitor#172]
### Checklist

- [X] I made sure that there are no similar feature requests - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details in an appropriate descriptive way. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Describe the Feature you'd like

Is it possible to add a daily quota alert of data used depending on the total monthly data set. For instance if the total monthly data limit is 5GB, then the daily quota would be 166MB. If an alert can fire when this daily quota is reached. 

### Why do you want this feature?

For instance if the total monthly data limit is 5GB, then the daily quota would be 166MB. If an alert can fire when this daily quota is reached.

**Comment by rosenclosed** [comment]
Addition: 

Base the Daily Quota on the leftover data for the billing period, put simply: 
Divide the leftover data for the billing period by the leftover days in the billing period

Also Daily Quota should be viewable in a sticky notification

I used to use GlassWire and switched to Data Monitor and this is one of the main features I happen to be missing a lot
