### ISSUE TITLE
Last week filter 

### ISSUE THREAD

**Issue by orschiro** [itsdrnoob/DataMonitor#178]
Hi all

Currently there is a filter for today, yesterday, this month, last month but I am missing last week in this selection.

Anyone else?

**Comment by itsdrnoob** [comment]
There is no "Last week" filter currently available. You can use the weekly overview to see the total data usage for the week.

**Comment by orschiro** [comment]
Thanks! The weekly overview doesn't give me a detailed overview, however. 

I would like to know which apps specifically consumed how much data last week.
