### ISSUE TITLE
unnecessary connection

### ISSUE THREAD

**Issue by SynapseScribe** [itsdrnoob/DataMonitor#180]
### Checklist

- [X] I made sure that there are no similar feature requests - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details in an appropriate descriptive way. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Describe the Feature you'd like

when performing diagnostics (network speed test) app connects to datamonitorweb.vercel.app for no obvious reason and unknown traffic being sent/downloaded
blocking the connection (with a firewall) prevents diagnostics from completion even if the test speed should be performed on speedtest.ftp.otenet.gr:80 instead (as defined on settigns > network diagnostics > download server)

### Why do you want this feature?

app shouldn't make unexpected connections posing security/privacy risks

**Comment by itsdrnoob** [comment]
The connection isn't unwanted.
During network diagnostics, the app secificallly fetches data from **https://datamonitorweb.vercel.app/ipLookup**, which returns details like IP address, connected server region, network provider etc.

The API itself is open source, and can be found [here.](https://github.com/itsdrnoob/DataMonitorWeb)

**Comment by SynapseScribe** [comment]
thank you for the explanation

**Comment by soshial** [comment]
I wish there were a version of DataMonitor without network speed test and without `android.permission.INTERNET`. I don't quite understand why to put this functionality together. It could be another app.

**Comment by SynapseScribe** [comment]
> I wish there were a version of DataMonitor without network speed test and without `android.permission.INTERNET`. I don't quite understand why to put this functionality together. It could be another app.

from my observations, app connects to internet only when performing network speed test. i suppose you can simply block internet access for the app if you don't want to use this feature. but it's true that a speed test shouldn't belong in an app with focus on monitoring data usage..

btw there is another open source app called application manager (short AM) that includes data/wifi network monitoring. however the stats differ slightly for some reason..
