### ISSUE TITLE
Monthly data plan that starts on custom dates

### ISSUE THREAD

**Issue by MintHawk** [itsdrnoob/DataMonitor#182]
### Checklist

- [X] I made sure that there are no similar feature requests - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details in an appropriate descriptive way. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Describe the Feature you'd like

Hello.
I would like to be able to set my monthly data plan beginning on, e.g., the 3rd day of the month which goes on until, e.g., the 2nd day of the next month.
Additionally, it would be nice if this plan could automatically be renewed from then on.
This happens because the monthly bill may start not on the 1st day of the month (at least in my country).
Many thanks.
S. Dimopoulos 

### Why do you want this feature?

It does not exist.

**Comment by itsdrnoob** [comment]
> I would like to be able to set my monthly data plan beginning on, e.g., the 3rd day of the month

You can change the start date for monthly plans from Setup. Also, monthly plan repeats automatically.

**Comment by MintHawk** [comment]
Thank you for the answer.
No, it doesn't start automatically.
Is there a setting I'm missing?

**Comment by MintHawk** [comment]
Is it the Auto Update Data Plan?

**Comment by itsdrnoob** [comment]
Monthly plan, just like a daily plan, should restart automatically from the specified starting date.

Auto update data plan is specific to custom data plans and doesn't have any effect on monthly plans.

Try clearing the app data and set a new monthly plan and check if that helps.

**Comment by MintHawk** [comment]
Ok, I will try that.

**Comment by MintHawk** [comment]
When I click on Monthly Plan, there is no value to select so I can start
the month on the 4th.

**Comment by itsdrnoob** [comment]
![IMG_20230608_142625](https://github.com/itsdrnoob/DataMonitor/assets/52557407/b32e23c6-bad0-4b2e-a5ad-43dd06fc5ad8)
Select the "Add data plan" option to add a data plan.
Then choose "Data usage reset date" to select the date.

**Comment by MintHawk** [comment]
Thank you. I'm an idiot I didn't notice that before...I appreciate the
instant help.
