### ISSUE TITLE
For the "This week's overview" chart, exactly when does the new week start?  

### ISSUE THREAD

**Issue by dln949** [itsdrnoob/DataMonitor#189]
For the "This week's overview" chart, exactly when does the new week start?  

And, how do I make that chart always update itself each day to always show the last seven days, instead of a fixed week?

**Comment by itsdrnoob** [comment]
> For the "This week's overview" chart, exactly when does the new week start?

The weekdays are clearly mentioned below the chart, from Monday to Sunday.

> how do I make that chart always update itself each day to always show the last seven days, instead of a fixed week?

You don't. The chart shows the current week's data usage overview (hence the name "This weeks overview").

**Comment by dln949** [comment]
What I meant is, when does the current week switch to the new week?  At midnight local time on Monday?  Or at a different time?

**Comment by itsdrnoob** [comment]
Yes, the week starts every Monday at midnight.

**Comment by dln949** [comment]
ok, thanks much
