### ISSUE TITLE
2 different translation Webseites

### ISSUE THREAD

**Issue by Tobias-Lauerbach** [itsdrnoob/DataMonitor#21]
**Describe the bug**
There are 2 different Translation Websites

**To Reproduce**
1. languages and klich de "help
us by [...]" banner -> first website
2. Go in github read me click contribute -> 2. website

**Expected behavior**
Only one website

**Comment by itsdrnoob** [comment]
The in-app link was an old one. Thanks for pointing it out. I'll update the link.
