### ISSUE TITLE
Split download and upload live speed in status bar

### ISSUE THREAD

**Issue by robsmith11** [itsdrnoob/DataMonitor#233]
### Checklist

- [X] I made sure that there are no similar feature requests - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details in an appropriate descriptive way. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Describe the Feature you'd like

Rather then a single aggregate network transfer rate, it would be useful to see separate download and upload rates like the built-in network speed monitor for LineageOS. 

### Why do you want this feature?

It's useful to see both speeds.

**Comment by itsdrnoob** [comment]
@robsmith11 You can expand the notification to see both upload and download speed seperately.

**Comment by robsmith11** [comment]
> @robsmith11 You can expand the notification to see both upload and download speed seperately.

Sure, and I could also run a command line tool in Termux to get network usage, but the advantage of being in the status bar is that it's always visible at a glance.  Much more useful without having to swipe down twice to see the notification each time I want to know whether the network usage is download or upload.

**Comment by itsdrnoob** [comment]
> Sure, and I could also run a command line tool in Termux to get network usage

So you're comparing an extra swipe/tap with running a command line tool?
Anyways, there are plans to update the notifications so I'll keep this in mind, thanks.
