### ISSUE TITLE
add button to pause/stop the the monitor

### ISSUE THREAD

**Issue by y1111** [itsdrnoob/DataMonitor#234]
### Checklist

- [X] I made sure that there are no similar feature requests - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details in an appropriate descriptive way. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Describe the Feature you'd like

a button on the app first screen and on the notification to pause/stop it

### Why do you want this feature?

because the app keeps running 24/7 . keeping processes in the background , using battery .

**Comment by y1111** [comment]
all(or most) other network related apps have this . like adaway ,1111 , nextdns , rethinkdns , netguard , vpn apps ,etc

**Comment by y1111** [comment]
by now, the only way to stop it  is to open app info and >force stop . (which is not ideal , have to hold for seconds app icon ) 
is better for the own app to have it. also to start again faster not needing to reload/restart all the app

**Comment by itsdrnoob** [comment]
Background running of the app depends on the enabled options. Features like Data usage notification / Live network speed requires that part of the app to be alive in order to work properly. Simply disable these options and the app won't be running in the background.

> start again faster not needing to reload/restart all the app

That is bound to happen when the app is force stopped.

**Comment by y1111** [comment]
yeah the app need to run in the background , it doesnt need to be changed or disabled. it runs correctly . 
the only thing it needs is a button to stop it whenever the user wants.

**Comment by itsdrnoob** [comment]
> stop it whenever the user wants.

If by this, you mean stopping the app, it's as simple as disabling the notifications/alerts from within the app.
