### ISSUE TITLE
Related to widgets

### ISSUE THREAD

**Issue by ShubhamPru** [itsdrnoob/DataMonitor#26]
The problem is in miui the widget is not fully compatible plz reduces the dp of the wedget or make the widget biger apply the widget in miui and see the issue
![Screenshot_2022-08-01-19-23-45-591_com miui home](https://user-images.githubusercontent.com/96346814/182163605-1888bc1b-dc27-4f27-b97b-c31cc0c41f6e.jpg)

**Comment by itsdrnoob** [comment]
This is a known bug, the widget is not really resizable so the current workaround is to change your home screen grid size. This will be fixed soon.

**Comment by ShubhamPru** [comment]
Ok thanks for replying. but plz fix this issue if it's possible in default 5×6 its the same and max grid by default launcher. Anyways I'll suggest to make a telegram support group it'll be so greatfull for every one so much ppl is also appreciating this apk

**Comment by itsdrnoob** [comment]
Correct me if I'm wrong but I don't think we have a big enough user base for a telegram support group.

**Comment by ShubhamPru** [comment]
Yeah user want u to made a telegram support group 🥲 I'll help u in management of group. u just join the group

**Comment by itsdrnoob** [comment]
Maybe you're right, a support group will be helpful. Lemme see what i can do.

**Comment by itsdrnoob** [comment]
> Yeah user want u to made a telegram support group

Check [datamonitor](https://t.me/datamonitor)
