### ISSUE TITLE
[Feature Request] Show actual data usage in data consumption graph.

### ISSUE THREAD

**Issue by starry69** [itsdrnoob/DataMonitor#27]
Hi! First of all thank you for the amazing app, it looks really neat.

I wanna suggest some features/improvements as follows:
1. How about showing actual data usage instead of 2.5gb+ on the data usage graph shown in home screen?
2. When clicking on wifi or mobile data card,
![IMG_20220804_093152_679](https://user-images.githubusercontent.com/58552395/182760412-533bf2f6-3a5f-495a-99e0-026866d17367.jpg)
you can redirect user to this page:
![Screenshot_2022-08-04-09-26-06-611_com drnoob datamonitor](https://user-images.githubusercontent.com/58552395/182761908-ed5a59f1-7033-4543-b308-8980963dfcea.jpg)

I think it'll be good for quick access from home screen.
Thanks again!

**Comment by itsdrnoob** [comment]
> Hi! First of all thank you for the amazing app, it looks really neat.

Thank you.

> How about showing actual data usage instead of 2.5gb+ on the data usage graph shown in home screen?

The '2 GB+' is a common measure for the entire week's data usage and cannot be replaced as data usage will be different each day. The concept is nice and I'll surely consider implementing it in a different way (like on top of the bar or on the actual bar itself).

The 2nd one is also quite good. Will consider it as well.
