### ISSUE TITLE
Network Diagnostics not working Properly

### ISSUE THREAD

**Issue by aishwarya85** [itsdrnoob/DataMonitor#29]
I tried using app multiple times but network diagnostics is not working properly.

Can you please change the entire network diagnostics with some other?

**Comment by itsdrnoob** [comment]
> I tried using app multiple times but network diagnostics is not working properly.

Can you elaborate yourself? Because I just tried it and it's working fine on my end.

> Can you please change the entire network diagnostics with some other?

I don't actually understand what you mean by 'some other' here.

**Comment by aishwarya85** [comment]
Instead of using ipinfo for network diagnostic can we use some other and also with some other ui. Such as speed test by ookla ui.


In current network diagnostic if you try testing with mobile data there is some issue. Might be if I am using angain and again with same ip. But issue is there.
I will share screen recording if possible

**Comment by itsdrnoob** [comment]
> Instead of using ipinfo for network diagnostic can we use some other

ipinfo is just used to get the ip details and doesn't have anything to do with speed test.

> also with some other ui. Such as speed test by ookla ui.

I like to keep the ui as simple and clean as possible without much clutter. But improvements will be done in the future.

> In current network diagnostic if you try testing with mobile data there is some issue. Might be if I am using angain and again with same ip. But issue is there

I've tried multiple times without facing any issue. It'd be helpful if you could elaborate the issue, send logs, or maybe the screen recording as you said.

**Comment by aishwarya85** [comment]
OK.
#I like to keep the ui as simple and clean as possible without much clutter. But improvements will be done in the future.
Is it possible to show real time speed on screen?

**Comment by itsdrnoob** [comment]
Showing live speeds can be done. I'll consider including it it future releases.

**Comment by aishwarya85** [comment]
https://imgur.com/a/UWbycjY

Connected Server : null

**Comment by itsdrnoob** [comment]
> Connected Server : null

Okay i'll need to know a few things.

- Are you running the latest version?
- Are you running your own build of the app?
- Can you provide me the logs?

**Comment by Terkyz** [comment]
> 
I'm expericing the same problems than OP, so I think I can answer

1. Yes. Downloaded from Github.
2. No.
3. Of course, how?

**Comment by itsdrnoob** [comment]
> Of course, how?

- Connect phone via adb
- Type `adb logcat --pid=$(adb shell pidof -s com.drnoob.datamonitor) > networkdiagnostics.log` into terminal
- Start network diagnostics
- Wait till it's connected and showing null/ the app crashes
- Stop logging and paste the logs into pastebin.com and send the link

**Comment by aishwarya85** [comment]
Instead of using ipinfo for network diagnostic can we use some other and
also with some other ui. Such as speed test by ookla ui.


In current network diagnostic if you try testing with mobile data there is
some issue. Might be if I am using angain and again with same ip. But issue
is there.
I will share screen recording asap.

**Comment by itsdrnoob** [comment]
> Instead of using ipinfo for network diagnostic can we use some other and
also with some other ui

As i said, ipinfo is just for gathering the ip information. And UI will be updated in future updates.

> In current network diagnostic if you try testing with mobile data there is
some issue

The current server used to test upload/download is currently down. I've switched the server and will take effect in the next update.
