### ISSUE TITLE
Data Monitor crashes upon giving usage access

### ISSUE THREAD

**Issue by Hell01World** [itsdrnoob/DataMonitor#32]
**Describe the bug**
After installing this app and giving it usage access, it crashes everytime I open it.

**To Reproduce**
1. Install the app from the GitHub releases page
2. Turn off battery optimisation
3. Give usage access
4. App crashes

**Expected behavior**
App to work normally

**Screenrecording**
https://pixeldrain.com/u/CQPU7uFm (hosted on pixeldrain, hope you don't mind. Recorded as a mp4 file)

**Smartphone (please complete the following information):**
 - Device: Oppo A31
 - OS: ColorOS V6.1.2, Android 9
 - App version: 1.6.9

### Important additional context
I used [Universal Android Debloater](https://github.com/0x192/Universal-Android-Debloater) to remove from the user 0 system apps such as Google Play Services, Google Play Store etc. without root via ADB.
Here is a full list of uninstalled apps: https://pastebin.com/RTGUE5ZZ 
And here is the description for it: https://raw.githubusercontent.com/0x192/universal-android-debloater/main/resources/assets/uad_lists.json

**Comment by itsdrnoob** [comment]
I wonder what's causing that. Can you get me the logs?

**Comment by Hell01World** [comment]
> Can you get me the logs?

Sure https://pastebin.com/hnxzppVS
This is the first time I'm sending a crash log, so I'm not sure if I did it correctly. I used this command: `adb logcat AndroidRuntime:E *:S`
As I said in the previous comment, I removed Google Play Services, so if the app depends on it then you got your anwser.

**Comment by itsdrnoob** [comment]
> if the app depends on it then you got your anwser.

I was wondering the same too. I'll have a look at the logs. In the meantime, the quickest way to find out will be to enable Google Play Services and recheck.

**Comment by itsdrnoob** [comment]
@Hell01World can you check if READ_PHONE_STATE permission is granted to the app.

**Comment by Hell01World** [comment]
> the quickest way to find out will be to enable Google Play Services and recheck.

Ok, so I installed Your app on my second phone that have removed Google Play Services via ADB and... it works https://pixeldrain.com/u/McdLSM7q

So I tried installing it on my Nintendon't Switch running LineageOS without any Google blobs and it worked as well https://pixeldrain.com/u/7uYAZ1pL

Summing up, for some reason Your app crashes on my Oppo phone.

**Comment by Hell01World** [comment]
> @Hell01World can you check if READ_PHONE_STATE permission is granted to the app.

I went to App info > Permissions and enabled access to "Phone" and now it works! Thank You for your time
