### ISSUE TITLE
Project Translation

### ISSUE THREAD

**Issue by shuvashish76** [itsdrnoob/DataMonitor#37]
Integrate [Weblate](https://github.com/WeblateOrg/weblate) for translation purpose.

Features: https://weblate.org/en/features/
![Screenshot_2021-12-05-21-15-09](https://user-images.githubusercontent.com/48226312/144753433-4fc61e84-f12d-42d0-885e-1b9abd399061.jpeg)
https://weblate.org/en/hosting/

**Comment by itsdrnoob** [comment]
Thanks, will look into it.

**Comment by comradekingu** [comment]
https://github.com/itsdrnoob/DataMonitor/pull/39/files would help smooth out the process of translating the app. :)

**Comment by comradekingu** [comment]
@itsdrnoob 
The translation on Weblate targets strings/en.xml https://hosted.weblate.org/projects/datamonitor/strings/#alerts
whereas the real file is
app/src/main/res/values/strings.xml

I can fix it if you add "kingu" in https://hosted.weblate.org/access/datamonitor/#users :)

**Comment by itsdrnoob** [comment]
@comradekingu I've added you as an administrator.

**Comment by comradekingu** [comment]
@itsdrnoob 
Seems to work now https://github.com/itsdrnoob/DataMonitor/pull/46 but it only tracks master in and out.
I was an idiot and saved my nb_NO glossary work instead of the actual strings. X)

**Comment by itsdrnoob** [comment]
@comradekingu 
I changed the branch to release/2.0.0 .

> saved my nb_NO glossary work instead of the actual strings. X)

;)
