### ISSUE TITLE
Wrong translation license

### ISSUE THREAD

**Issue by comradekingu** [itsdrnoob/DataMonitor#38]
https://hosted.weblate.org/projects/datamonitor/strings/#information says proprietary, but
https://github.com/itsdrnoob/DataMonitor/blob/release/1.6.9/LICENSE says GPLv3

These are incompatible with each-other.

Would be better to have both be GPLv3+, which can be done from
https://hosted.weblate.org/settings/datamonitor/strings and
https://hosted.weblate.org/settings/datamonitor//glossary

#37 related

**Comment by itsdrnoob** [comment]
The project is licensed under GPLv3. I've just added the project on weblate. It's neither set up properly nor have I requested the status of FOSS for the project. And is not yet ready for translations. As of now, Translations have to be done either on Poeditor or by forking the repo.

**Comment by comradekingu** [comment]
(I am happy to re-license mine for nb_NO to GPLv3+.)

**Comment by itsdrnoob** [comment]
> (I am happy to re-license mine for nb_NO to GPLv3+.)

Sure thing, I've already changed the project's translation license.
