### ISSUE TITLE
Notification layout improvement

### ISSUE THREAD

**Issue by iBabu007** [itsdrnoob/DataMonitor#42]
**Is your feature request related to a problem? Please describe.**

Please Improved it's notification panel.
And add more customization option inside setting.

If possible then add separate Notification setting inside setting.

**Describe the solution you'd like**
Reduced it's notification panel size or compact notification panel. 

**Describe alternatives you've considered**

**Additional context**
See this images
![Screenshot_20220902-110529](https://user-images.githubusercontent.com/65340361/188271067-8a7875ad-0176-4b64-9daf-ab55e5ec3244.png)

![Screenshot_20220902-110143](https://user-images.githubusercontent.com/65340361/188271069-bc2db2ab-031f-459a-b64e-01eab09befb3.png)

![Notification layout 2](https://user-images.githubusercontent.com/65340361/188271075-2d1c6988-6f6b-4dfc-abc9-6006b29dff1e.jpg)

![Notification layout](https://user-images.githubusercontent.com/65340361/188271077-318275ea-17cc-418e-8c99-70f6b6196388.jpg)

**Comment by itsdrnoob** [comment]
> And add more customization option inside setting.

Please elaborate yourself, like what customisation settings are you thinking of.

And yes, I'll consider the custom notification layout idea.

**Comment by anuraag488** [comment]
![Screenshot_20221115-060312_Fennec](https://user-images.githubusercontent.com/7353086/201797700-6abfcf6e-e718-4e9a-b91a-aaa9f8ec9606.png)

I would like to see a single notification for total data used and speed like above screenshot.

**Comment by itsdrnoob** [comment]
@anuraag488 the issue with this approach is that the icon of both notifications has a different purpose (one shows network speed and the other shows the % of data used).
I'll still try to implement an option to combine both as one.

**Comment by BahrawiGuide** [comment]
@itsdrnoob Yes, it is possible to make the live network speed monitor notification contain all the data and keep the show the % of data used notification displayed as it is for those who want to enable it.

**Comment by Pranab009** [comment]
If possible then combined all thing together 
at notification panel.
![Notification layout 2](https://user-images.githubusercontent.com/65340361/202984556-3442deb4-496b-4319-9936-b3c12b3a51c0.jpg)

**Comment by iBabu007** [comment]
If possible then combined all thing together 
at notification panel.
![Notification layout 2_1](https://user-images.githubusercontent.com/65340361/202985398-02595d64-24ff-443d-8e68-258f3d2f6ff9.jpg)

See this image. All important data is available here with compact size.
