### ISSUE TITLE
Auto start on boot

### ISSUE THREAD

**Issue by shuvashish76** [itsdrnoob/DataMonitor#44]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when I restart the device but the data monitor feature (_which is implemented with v2_) doesn't auto start.

**Describe the solution you'd like**
Add an option to Enable/Disable auto start on boot.

**Comment by itsdrnoob** [comment]
> I'm always frustrated when I restart the device but the data monitor feature (which is implemented with v2) doesn't auto start

This is more like a bug, than a feature request. I got that the service is not starting automatically on boot, as expected. I'll be fixed in the next update.
