### ISSUE TITLE
Network speed graph on status bar

### ISSUE THREAD

**Issue by shuvashish76** [itsdrnoob/DataMonitor#49]
Display network speed graph in a status bar notification.

![image](https://user-images.githubusercontent.com/48226312/190335115-9869d5b9-d091-4513-91ba-e76c4231bbfb.png)

(_from [NetGuard](https://github.com/M66B/NetGuard)_)

**Comment by itsdrnoob** [comment]
I don't see how live display of network speed as a graph in notification is really worth the battery sacrificed.
