### ISSUE TITLE
Network diagnostics not working

### ISSUE THREAD

**Issue by Master2050** [itsdrnoob/DataMonitor#53]
**Describe the bug**
Network diagnostics takes forever left it running for 5 minutes and nothing happened

**To Reproduce**
1. Go to network diagnostics tab
2. Click on run diagonistics
3. Animation plays and nothing happens

**Expected behavior**
Network diagnostics should be performed

**Screenshots**
Keeps loading forever

![Screenshot_2022-10-26-06-35-24-40_4658bfd74d73f2a7c13010ce808ba7ad](https://user-images.githubusercontent.com/28833686/197910692-f22df151-e3df-4f49-a0ee-1ab9b8850679.png)

**Smartphone (please complete the following information):**
 - Device: Oppo Real me 1 CPH1861
 - OS: Color OS v6.0 (Android 9)
 

**Additional context**
Maybe something related to diagnostics server. Maybe add option to choose more diagnostics services as there are plenty available on web.

**Comment by shuvashish76** [comment]
Please provide the app version you're using.
Duplicate #29

**Comment by itsdrnoob** [comment]
As I mentioned in #29, the server is currently down.

> Maybe add option to choose more diagnostics services as there are plenty available on web.

Will think about that as well.

**Comment by itsdrnoob** [comment]
> Probably reduces app size making it lightweight

The app size is already 4.9 MB on Play Store and around 6.5 MB as apk. I think that is pretty lightweight.

**Comment by itsdrnoob** [comment]
Will not add a webview for sure. Sites may contain ads (which could be mistaken for an ad built into the app) or other trackers. And as far as opening up a browser is conserned, one can do that manually as well.

**Comment by killerrook** [comment]
Also close #29 don't need duplicate issues anyways
