### ISSUE TITLE
App crashes when clicked on a non system app

### ISSUE THREAD

**Issue by Master2050** [itsdrnoob/DataMonitor#54]
**Describe the bug**
App crashes when clicked on a non system app for info about data sent and data received 

**To Reproduce**
1. Open the app
2. Click on mobile data denoted by a red antenna icon
3. Scroll down to any non system app 
4. Click on app for more info 
5. App crashes after 2-3sec

**Expected behavior**
App should show more info about data sent and received by the selected app

**Screenshots**
Step 2
![Screenshot_2022-10-27-01-31-47-13_4658bfd74d73f2a7c13010ce808ba7ad](https://user-images.githubusercontent.com/28833686/198125796-6f9d98e1-92d0-45a3-b6c8-da9a56d288c0.png)

For step 3 and 4

![Screenshot_2022-10-27-01-31-17-41_4658bfd74d73f2a7c13010ce808ba7ad](https://user-images.githubusercontent.com/28833686/198125930-64c4ca16-39f6-4db5-b740-92bce8c4d072.png)

 just before crashing

![Screenshot_2022-10-27-01-31-09-89_4658bfd74d73f2a7c13010ce808ba7ad](https://user-images.githubusercontent.com/28833686/198126067-4e72874b-0495-492e-a76f-49ef5ae6408f.png)

**Smartphone (please complete the following information):**
 - Device: Oppo Real me 1 CPH1861 Non rooted
 - OS: Color OS v6.0 
 - App Version 2.0.0

**Additional context**

**Comment by itsdrnoob** [comment]
- Does this happen every time?
- I can see in the screenshot for step 3 & 4 that apps appear twice. This is due to the function running twice and and loading half-baked data into the list. This is a bug and is (hopefully) fixed in the upcoming version. So the crash was probably due to this issue.

**Comment by itsdrnoob** [comment]
If it happens every time, even when the apps appear once, then it might be some other issue. 
Have you granted all permissions?
Could be related to #41 but not sure. 
Can you grab logs?

**Comment by itsdrnoob** [comment]
Strange, seems like accessing screen time data is causing the error. 
Is there any additional permission in ColorOS that I'm unaware of?

> get a logcat inbuilt in the app to catch crash reports

Crash reporter has been implemented in the app for upcoming versions. I can provide you with a build for reporting logs. Can you pm me on [telegram](http://t.me/itsdrnoob) ?

**Comment by itsdrnoob** [comment]
> sorry don't use telegram

That's alright, you can drop me a [mail](mailto:itsdrnoob@gmail.com)

**Comment by itsdrnoob** [comment]
> Clicking on anything other than github will simply close the app

Will check what's happening here.

> The app doesn't even have an option to copy logs

When you select github, it automatically copies the crash logs to clipboard.

> The scaling of text is also incorrect 

Will be fixed

**Comment by itsdrnoob** [comment]
> Your crash reporter should allow at least ability to copy crash logs

Yeah, will add an option to manually copy logs

**Comment by itsdrnoob** [comment]
> Also make debug version separate from original app

Debug version is not released. Only release builds are available for download.

**Comment by itsdrnoob** [comment]
> Copy data button still doesn't work

Because there were no logs to copy as happened in earlier cases.

> Here is the log obtained

Is that all? I don't see any crash logs here.

**Comment by itsdrnoob** [comment]
> Yup that's all it gives in a text file

That's odd. I am still wondering what the issue might be, as it's not even throwing any crash logs.

**Comment by itsdrnoob** [comment]
> Yup the latest app you sent fixed the problem of crash

:)


> permission denied toast still appears

I haven't done anything about it yet. Will look into it.

> Shall i close this issue now

Nope, will push the fix first.
