### ISSUE TITLE
Cant go back to home tab from data usage tab

### ISSUE THREAD

**Issue by Master2050** [itsdrnoob/DataMonitor#55]
**Describe the bug**
Cant go back to home tab from data usage tab

**To Reproduce**
1. Open app
2. Click on red antenna icon depicting mobile data
3. Click on home tab
4. Nothing happens

**Expected behavior**
App should show me the home tab containing info about net mobile and WiFi data usage

**Screenshots**
See the video

https://user-images.githubusercontent.com/28833686/198200488-8ad2e650-b629-45a4-80ab-b888f130559c.mp4

**Smartphone (please complete the following information):**
 - Device: Oppo Real me 1 CPH1861_A11_C50 non rooted
 - OS: Color OS v 6.0(Android 9)
 - Version v2.0.0

**Additional context**

**Comment by itsdrnoob** [comment]
Known issue as mentioned in #50. Fixed in d7ab932c09cef109198779087ce79de3cf18b4fd
