### ISSUE TITLE
Custom period data usage

### ISSUE THREAD

**Issue by heberjeur** [itsdrnoob/DataMonitor#57]
**Describe the solution you'd like**
Hi, can you add a custom period data usage for WiFi and mobile data monitor

**Describe alternatives you've considered**
Currently I use Glasswire that do that
![Screenshot_20221030-114839_GlassWire](https://user-images.githubusercontent.com/11852634/198874670-3ca21832-f043-40b4-aee9-bc0d5d55dc36.jpg)

**Comment by itsdrnoob** [comment]
Already implemented. Check da3e476f8180f7cfa33436c96c442927ea4a6ebc
