### ISSUE TITLE
Day by day data usage stats

### ISSUE THREAD

**Issue by heberjeur** [itsdrnoob/DataMonitor#58]
**Describe the solution you'd like**
Hi, can you add an option to navigate per day my data

**Describe alternatives you've considered**
Can you add a daily data tracking, similar to that..

![Screenshot_20221030-115048_GlassWire](https://user-images.githubusercontent.com/11852634/198874928-4938fc8f-1f8d-45b1-bd3f-d2bc5ed2c803.jpg)

**Comment by itsdrnoob** [comment]
Will consider this for future updates.

**Comment by killerrook** [comment]
Day by day data usage stats is likely more descriptive and appropriate title
