### ISSUE TITLE
Error while running app in android studio

### ISSUE THREAD

**Issue by aishwarya85** [itsdrnoob/DataMonitor#6]
Error while doing Network diagnostics.

App gets forced close while doing Network diagnostics.

**Comment by itsdrnoob** [comment]
Please provide some more details.
1. Are you running the latest version (v1.5.1)?
2. Are you running the app in an emulator?

Check if you can:
1. Provide the steps to reproduce the issue
2. Provide logs

**Comment by aishwarya85** [comment]
I had downloaded code copy today only.

But its showing v1.5 in about.

I have recorded video. Link is below.

https://drive.google.com/file/d/18ovqudIQVT5y2B-sEH-OivdC_VF17otX/view?usp=sharing

**Comment by itsdrnoob** [comment]
If you're running your own build from android studio, you need to specify your api key in app/src/main/jni/keys.c

Also thanks for pointing out the version naming issue, I'll update the repo shortly

**Comment by aishwarya85** [comment]
#include <jni.h>

JNIEXPORT jstring JNICALL
Java_com_drnoob_datamonitor_ui_fragments_NetworkDiagnosticsFragment_getApiKey(JNIEnv *env,
                                                                              jobject instance) {
    // TODO: implement getApiKey()
    return (*env)->  NewStringUTF(env, "https://ipinfo.io/123.201.0.141/json?token=33181374b257ec"); // Base64 encoded Api key from https://ipinfo.io/
    
    return (*env)->  NewStringUTF(env, "33181374b257ec");
    
}

I tried doing so but not working

**Comment by itsdrnoob** [comment]
You need to encode your key first using Base64.
You can encode your key [here](https://www.base64encode.org) and replace <API_KEY> with the encoded key.

**Comment by aishwarya85** [comment]
ohhh...

I thought they gave us encoded key.

Its done thank u
