### ISSUE TITLE
Data Usage in Status Bar

### ISSUE THREAD

**Issue by n-ce** [itsdrnoob/DataMonitor#60]
**Is your feature request related to a problem? Please describe.**
Its an extra fuss to slide over to the notification panel and look at the data usage there.

**Describe the solution you'd like**
Showing data usage directly in status bar like network speed indicator.

**Describe alternatives you've considered**
Did not find any other alternatives other than compromising on my ux.

**Additional context**
NaN

**Comment by itsdrnoob** [comment]
Showing the data usage as an icon would require a lot more drawables and will end up increasing the size of the app. Which can be avoided by just one extra swipe to the home screen or notification bar.

**Comment by n-ce** [comment]
Could you tell me why this is not the case with speed indicator?

**Comment by itsdrnoob** [comment]
This is exactly the case with the speed indicator. To do the same with data usage, it would need a lot more icons. Let's say a user consumed 5.7 GB of data, to show the usage as an icon, it would require icons upto 5.7 GB (at least).

**Comment by n-ce** [comment]
I had a feeling implementing this would have limitations given none of the data monitor apps has done this yet.
I have some ideas about how to do this that i would like to discuss in length. Is this the appropriate place?

**Comment by itsdrnoob** [comment]
> I had a feeling implementing this would have limitations

It sure does have its own limitations

> I have some ideas about how to do this that i would like to discuss in length. Is this the appropriate place?

You are free to join the telegram [support group](https://t.me/datamonitor)

**Comment by n-ce** [comment]
Excited for the next release! 🤩
Thank you!
