### ISSUE TITLE
App shows permission denied toast before granting READ_PHONE_STATE permission

### ISSUE THREAD

**Issue by Master2050** [itsdrnoob/DataMonitor#62]
**Describe the bug**

**To Reproduce**
1. Install and open app
2. Grant required usage access permission 
3. The app shows permission granted 
4. Click on next and see the error toast notification 

**Expected behavior**
App should not show permission denied toast and also not contradict permission granted written on initially grant acces button

**Screenshots**
Edit: screenrecording removed for privacy reasons 

**Smartphone (please complete the following information):**
 - Device: Oppo Realme 1 CPH1861
 - OS: Color Os v 6.0(Android 9)
 - Version 2.0

**Additional context**
If i didn't provide app usage access how come it can show data usage.

**Comment by itsdrnoob** [comment]
I think it's for phone permission. The next button in usage access screen will only be shown once the permission is granted. Try granting phone permission manually.

**Comment by itsdrnoob** [comment]
> Updated the bug report see new video

As I can see in the video, the app started successfully. The message telling to grant permission maually was for phone permission which i will look into.

**Comment by killerrook** [comment]
Maybe consider adding bug label here?
