### ISSUE TITLE
Overlapping "no data available" visual bug

### ISSUE THREAD

**Issue by Master2050** [itsdrnoob/DataMonitor#64]
**Describe the bug**
A unnecessary message "no data available" overlapped on the data usage screen

**To Reproduce**
1. Open app
2. Click on per app data usage tab
 
Note: it is an occasional inconsistent bug aka hard to reproduce 

**Expected behavior**
App should display data usage without any overlapping message 

**Screenshots**
![Screenshot_2022-11-08-22-25-12-68_4658bfd74d73f2a7c13010ce808ba7ad](https://user-images.githubusercontent.com/28833686/200652259-2b4e4613-7b4e-43dc-b25e-428e09f52f2b.png)

**Smartphone (please complete the following information):**
 - Device: Oppo Realme 1 CPH1861
 - OS: Android 9 Color Os V6.0
 - Version: 2.0.0

**Additional context**
Nothing here just crickets

**Comment by itsdrnoob** [comment]
Fixed in v2.1.0

**Comment by killerrook** [comment]
Please fix network diagnostics aka speed test issues as well.

When will the update be rolled out?

**Comment by killerrook** [comment]
As of now v1.0 works really good for me.
No non working diagnostics (don't use anyways)
No crash as there is no app usage time 
4.2mb smallest possible size 
Simple and straightforward app

The only downside is i have to set phone permission manually which is not that big issue. Thanks for your app.

**Comment by itsdrnoob** [comment]
> Please fix network diagnostics

Network diagnostics is working fine in the new build.

> When will the update be rolled out?

Probably tomorrow. Waiting for the F-Droid build.

Both issues are fixed in the latest build.

> Thanks for your app.

:)
