### ISSUE TITLE
Add Portuguese (BR) language to the Data Monitor app

### ISSUE THREAD

**Issue by hectorg2208** [itsdrnoob/DataMonitor#66]
### Checklist

- [X] I made sure that there are no similar feature requests - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Is your feature request related to a problem? Please describe.

This feature is not related to a problem.

### Describe the solution you'd like

Just want you to, please, add Portuguese (BR) language to the app.

### Additional context

I have already translated the entire language on the help site provided in the Data Monitor app.

**Comment by itsdrnoob** [comment]
Portuguese has already been added as you can see in commit f6272b39469ccbef7ab7b258aa6b16733fef67f3
