### ISSUE TITLE
Show amount of data left in accordance with data plan 

### ISSUE THREAD

**Issue by killerrook** [itsdrnoob/DataMonitor#69]
### Checklist

- [X] I made sure that there are no similar feature requests - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Is your feature request related to a problem? Please describe.

I need to calculate the data left in accordance with my data plan

### Describe the solution you'd like

Show how much data is left according to the data plan settings 

### Additional context

I really don't have a problem.... Please change the template as:

Feature description:

---

Why do you want this feature?

----

Additional information:

**Comment by itsdrnoob** [comment]
Currently, the widget will show you the amount of data used with remaining/excess usage info.

> Please change the template as:

Why the template?

**Comment by killerrook** [comment]
> Why the template?

It is really awkward suppose if someone has a new idea but doesn't have a problem with the way the app works in current state. In that case he can write under why do you want this feature? Things like GUI enhancement, improves versatility of app, etc.

Asking for feature description first then asking for a good reason is a good template in my opinion.

> Currently, the widget will show you the amount of data used with remaining/excess usage info.

Don't use widget reason: unnecessary extra battery consumption, don't like widgets anyways

**Comment by itsdrnoob** [comment]
> It is really awkward suppose if someone has a new idea but doesn't have a problem with the way the app works in current state.

Yeah, does make sense.

> Don't use widget.

Will try to add a section in app.

**Comment by killerrook** [comment]
Here is a visual example with well written template 
![Screenshot_2022-11-12-22-53-18-98](https://user-images.githubusercontent.com/28833686/201486695-8bd839e6-d4d8-40f1-8d87-07a35d88b963.png)
