### ISSUE TITLE
Vibration toggle 

### ISSUE THREAD

**Issue by sanctimoniousape** [itsdrnoob/DataMonitor#74]
### Checklist

- [X] I made sure that there are no similar feature requests - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Is your feature request related to a problem? Please describe.

Changing date of plan reset involves scrolling through numbers (annoying when a calendar would be quicker), triggering the vibration motor.  I have nerve issues that make this... undesirable.  

### Describe the solution you'd like

Please stop using vibration needlessly, or at least provide an option to prevent it from working.  Better would be just to provide a calendar instead so if you must vibrate, then it's at least just one quick confirmation hit.

### Additional context

I know it seems like something little used, but I change plans routinely according to needs and deals I find. You already have a request open regarding plans that don't fit the traditional "specific date each month" format, so I'll not harp on that.

**Comment by itsdrnoob** [comment]
> triggering the vibration motor. I have nerve issues that make this... undesirable.

Understandable, will include an option to disable haptics.

And will look into switching to date picker.

**Comment by sanctimoniousape** [comment]
Wonderful!  Thanks for the quick response and understanding.
