### ISSUE TITLE
2x2 widget

### ISSUE THREAD

**Issue by xmha97** [itsdrnoob/DataMonitor#76]
### Checklist

- [X] I made sure that there are no similar feature requests - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Is your feature request related to a problem? Please describe.

I can't resize the widget to 2x2

### Describe the solution you'd like

I need a 2x2 widget like iOS widgets

![Screenshot_2022-11-14-23-30-52-690_com miui home](https://user-images.githubusercontent.com/23485114/201758096-01d9a196-0d3c-4da8-88e9-b0b35b8ebfd8.jpg)

**Comment by xmha97** [comment]
@xmha97

**Comment by shell-raiser** [comment]
Or atleast, would be better if its 3x1 when wifi usage is disabled

**Comment by itsdrnoob** [comment]
> Or atleast, would be better if its 3x1 when wifi usage is disabled

3x1 would still trim off some parts of the widget.
