### ISSUE TITLE
x days data plan

### ISSUE THREAD

**Issue by Przbl** [itsdrnoob/DataMonitor#77]
### Checklist

- [X] I made sure that there are no similar feature requests - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Is your feature request related to a problem? Please describe.

My data plan runs for 28 days (4 weeks). 
This is a common range here, unfortunately it's not covered by the app.

I found open and closed issues that deal with data plan periods, but none of them seem to request 'x days' periods. 

### Describe the solution you'd like

Independent from the 'nth of month' or month generally it would be good to have an exact start date like '2022-11-25' and an amount of weeks (like '4') or days (like '28') that defines the plan period.

**Comment by itsdrnoob** [comment]
You can add a custom data plan for x number of days.

**Comment by Przbl** [comment]
You mean like in the next update? Or did I miss a setting?

The current version (2.1.0) only allows a custom period where you set a Start date (like the 7th of the month) and an end date (like the 25th of the same month).
What I was referring to is a plan that starts e.g. tomorrow (Nov 16th) and runs 28 days (to Dec 14th). There's no way to set that period. And after that 4 week period the next 28 days end on Jan 11.

**Comment by itsdrnoob** [comment]
You're right, currently you can only set a plan that starts and ends in the current month. Will update the custom plan to be more versatile in the next build.

**Comment by sivaraam** [comment]
> You're right, currently you can only set a plan that starts and ends in the current month. Will update the custom plan to be more versatile in the next build.

While at it, kindly also consider a custom plan whose duration is more than a month. Right now, the app only seems to be allowing start and end dates within a month. In India, some providers provide plans that run for 28, 56 and 84 days. So, it would be very helpful to be able to specify such a data plan using the app 🙂

**Comment by Przbl** [comment]
Thanks for your update, but I'm afraid we've misunderstood each other.

I just installed the new v2.20.
Now there's a custom data plan that allows start and end dates in different months. That's fine, but that still doesn't cover plans that run x days.

My data plan runs 4 weeks, that's 28 days. It started on 14.12.2022 and runs until 11.01.2023. With your last change, I can map this period; but only once, not for the following periods. So in January I have to manually configure the period again for 28 days, this time from 12.01.2023 to 09.02.2023. And so on, every 28 days.

What I meant was having just an option of setting a start date and an amount of days. So just one setup would cover the plan forever.

**Comment by itsdrnoob** [comment]
For now, you've to manually set the data plan each time. The option to auto repeat the data plan is not fully functional yet and is still under development.

**Comment by Aarekaz** [comment]
@Przbl Yeah, I also have the same data plan which expires after 28 days and I need to renew it again. It would be great for something like this to be set up, also with notifications when then plan is about to expire.
