### ISSUE TITLE
Disable widget background transparency

### ISSUE THREAD

**Issue by xmha97** [itsdrnoob/DataMonitor#78]
### Checklist

- [X] I made sure that there are no similar feature requests - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Is your feature request related to a problem? Please describe.

Add an option to disable widget background transparency.

![IMG_20221115_010832_398](https://user-images.githubusercontent.com/23485114/201771638-6c7d4417-904e-4979-8fbb-bbb4816cba6e.jpg)

### Describe the solution you'd like

Widgets of other apps isn't transparency.

**Comment by itsdrnoob** [comment]
Some parts of the widget is transparent. This is an intended feature.

**Comment by xmha97** [comment]
Is it possible to add this feature?

**Comment by itsdrnoob** [comment]
The widget was designed to be like that. So,
Possible? **Yes**
Planned? **No**
