### ISSUE TITLE
Adding time of App Used for daily and monthly basis.

### ISSUE THREAD

**Issue by aishwarya85** [itsdrnoob/DataMonitor#8]
**Adding time of App Used on a daily and monthly basis.**
Hello,

Everything working fine.
Is it possible to add time tracking or usage of apps with data used?

For example,
FB consumed 1 GB and the time used is 1.5 hrs like that?

It will make people time conscious as well as data usage conscious.

**Comment by itsdrnoob** [comment]
Good suggestion. I'll look into this once my exams are over.

**Comment by aishwarya85** [comment]
Hey are exams over??

Waiting for a new update eagerly.....

**Comment by itsdrnoob** [comment]
Thank you for your patience, but still 1 more to go. I'll start working on it soon.

**Comment by itsdrnoob** [comment]
An [update](https://github.com/itsdrnoob/DataMonitor/releases/tag/v1.6.0) has been pushed.
