### ISSUE TITLE
Auto language detection

### ISSUE THREAD

**Issue by AxusWizix** [itsdrnoob/DataMonitor#85]
### Checklist

- [X] I made sure that there are no similar feature requests - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details in an appropriate descriptive way. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Describe the Feature you'd like

Hi, make the application detect the system language and set the same language in the application, if it is in the application.

### Why do you want this feature?

Auto language detection

**Comment by Cwpute** [comment]
I've installed DataMonitor app twice just to be sure: on my phone this doesn't work.

It doesn't detect the language right.
When i go into the options, it's set to `English`, éut when i click on `System default` it rightfully detects the language as it should have from the start.

**Comment by itsdrnoob** [comment]
> It doesn't detect the language right.

Yes, by default the language is set to English and has to be manually changed to another one or system default. Will change it to use system language by default instead.
