### ISSUE TITLE
Doesn't Auto-rotate by default

### ISSUE THREAD

**Issue by shell-raiser** [itsdrnoob/DataMonitor#90]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/itsdrnoob/DataMonitor/releases/latest).
- [X] I made sure that there are no existing issues - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details in an appropriate descriptive way. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### Affected app version

2.1.0

### Steps to reproduce the bug

Open the app and try to rotate your screen

### Expected behavior

It should rotate to landscape automatically

### Actual behavior

Doesn't rotate to landscape, remains on portrait mode

### Affected Android/Custom ROM version

12, One UI

### Additional context

I'm filling it as a bug because force rotating it is not introducing any artifacts

**Comment by itsdrnoob** [comment]
Not a bug but an intended behaviour. The app is not properly optimised for landscape view, and is therefore disabled.

**Comment by shell-raiser** [comment]
Oh cool then
Just FYI, I didn't find any artifacts, so it might be an easy fix if you want to
