### ISSUE TITLE
excluding some application traffic in the data plan

### ISSUE THREAD

**Issue by Ben-md5** [itsdrnoob/DataMonitor#92]
### Checklist

- [X] I made sure that there are no similar feature requests - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed).
- [X] I have taken the time to fill in all the required details in an appropriate descriptive way. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Describe the Feature you'd like

Hope to add the function of excluding some application traffic in the traffic plan

### Why do you want this feature?

some operator won't measure some app's data in their data plan.

**Comment by reyespinosa1996** [comment]
@Ben-md5 That's s great feature and should be implemented ASAP as there is a lot of user affected by isp policy's (I'm one miself)
