### ISSUE TITLE
crash after trying to add a data plan

### ISSUE THREAD

**Issue by Playit3110** [itsdrnoob/DataMonitor#98]
----------Start of crash----------
Thread name: main
Thread stacktrace: [dalvik.system.VMStack.getThreadStackTrace(Native Method),
 java.lang.Thread.getStackTrace(Thread.java:1841),
 e.c.a.f.a.uncaughtException(Unknown Source:47),
 java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073),
 java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068),
 java.lang.Thread.dispatchUncaughtException(Thread.java:2306)]
crash message: For input string: "10,00"

----------Crash logs----------
[jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054),
 jdk.internal.math.FloatingDecimal.parseFloat(FloatingDecimal.java:122),
 java.lang.Float.parseFloat(Float.java:455),
 com.drnoob.datamonitor.ui.fragments.SetupFragment$SetupPreference$c$e.onClick(Unknown Source:49),
 android.view.View.performClick(View.java:7881),
 android.widget.TextView.performClick(TextView.java:16201),
 android.view.View.performClickInternal(View.java:7858),
 android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0),
 android.view.View$PerformClick.run(View.java:30863),
 android.os.Handler.handleCallback(Handler.java:942),
 android.os.Handler.dispatchMessage(Handler.java:99),
 android.os.Looper.loopOnce(Looper.java:226),
 android.os.Looper.loop(Looper.java:313),
 android.app.ActivityThread.main(ActivityThread.java:8741),
 java.lang.reflect.Method.invoke(Native Method),
 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571),
 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)]

----------Device info----------
Device Manufacturer: samsung
Device Brand: samsung
Device Model: SM-G780F
Device Codename: r8seea
Android version: 13, 33
SOC Model: Exynos 990

**Comment by Playit3110** [comment]
Error in floating number parsing. Im in Germany and we would right 2.34 as 2,34

**Comment by itsdrnoob** [comment]
> Error in floating number parsing. Im in Germany and we would right 2.34 as 2,34

The issue has been reported quite a few times, and is [fixed](https://github.com/itsdrnoob/DataMonitor/commit/199ffbda5a4387e1b75db48d844eaffc0b479f67). It'll be out with the next release. In the meantime you can try using "." while adding a data plan.

**Comment by Playit3110** [comment]
Thanks i will wait for it.

PS: wish you a nice christmas

**Comment by itsdrnoob** [comment]
> wish you a nice christmas

Thanks, You too :)
